### ISSUE TITLE
run on ddev mutagen

### ISSUE THREAD

**Issue by kszymukowicz** [a-r-m-i-n/ddev-for-typo3-extensions#4]
hi 

can you run this on ddev that supports mutagen?
Even If I disable mutagen for project I get error.

`Mutagen docker volume is not mounted. Please use ddev restart` 

Of course I am running `ddev restart` without any luck. The same error again.

**Comment by a-r-m-i-n** [comment]
Hello, I've never heard about this tool before.

After a quick google search, I've found this in the code of DDEV: https://github.com/drud/ddev/blob/master/pkg/ddevapp/ddevapp.go#L1059

If you still see this error message, this mutagen is still enabled. Maybe you need also to restart your command prompt? Or even the whole system?

Good luck!

**Comment by cyMarvin** [comment]
Just a quick update on this issue after I had some trouble with it as well after upgrading docker and ddev:

Mutagen seems to be enabled by default in new ddev projects and needs to be explicity disabled or configured correctly.
Adding `performance_mode: none` to _.ddev/config.yaml_ will disable it on project level and solve the problem for now.
https://ddev.readthedocs.io/en/latest/users/install/performance/#mutagen
